name: Apply Snyk ignores from CSV
description: Builds .snyk from .snyk-ignores.csv
inputs:
  csv:
    description: Path to CSV file
    default: .snyk-ignores.csv
runs:
  using: "composite"
  steps:
    - name: Install Snyk CLI
      uses: snyk/actions/setup@v4
    - name: Generate .snyk
      shell: bash
      env:
        SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
      run: |
        set -euo pipefail
        FILE="${{ inputs.csv }}"
        rm -f .snyk || true
        if [[ ! -f "$FILE" ]]; then
          printf '{"version":"v1.25.0","ignore":{}}' > .snyk
        else
          grep -v '^\s*#' "$FILE" | while IFS=, read -r id expiry reason; do
            id="$(echo "${id:-}" | xargs)"; [[ -z "$id" ]] && continue
            args=(--id="$id" --yes)
            [[ -n "${expiry:-}" ]] && args+=(--expiry="$expiry")
            [[ -n "${reason:-}" ]] && args+=(--reason="$reason")
            snyk ignore "${args[@]}" || true
          done
        fi
        echo "=== .snyk ==="; cat .snyk
