name: Docker Release
on:
  workflow_call:
    inputs:
      registry:       { type: string, default: "docker.io" }
      image_suffixes: { type: string, default: '["service","front"]' } # JSON array
    secrets:
      DOCKERHUB_USERNAME: { required: true }
      DOCKERHUB_TOKEN:    { required: true }

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ${{ fromJson(inputs.image_suffixes) }}
        include:
          - name: service
            context: ./app
            dockerfile: Dockerfile
            suffix: supermario-service
          - name: front
            context: ./web
            dockerfile: Dockerfile
            suffix: supermario-front
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.suffix }}
          tags: |
            type=ref,event=tag
            type=sha,format=short
            type=raw,value=latest,enable=${{ startsWith(github.ref,'refs/heads/') }}
      - id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Write image ref
        run: echo "${{ inputs.registry }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.suffix }}@${{ steps.build.outputs.digest }}" > image-${{ matrix.name }}.txt
      - uses: actions/upload-artifact@v4
        with:
          name: images-to-scan
          path: image-${{ matrix.name }}.txt
      - name: Attest provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ inputs.registry }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.suffix }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: false
      - name: SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ inputs.registry }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.suffix }}@${{ steps.build.outputs.digest }}
          format: spdx-json
          artifact-name: sbom-${{ matrix.name }}-${{ github.sha }}.spdx.json
          upload-artifact: true
