name: Playwright E2E
on:
  workflow_call:
    inputs:
      node_version: { type: string,  default: "20" }
      base_url:     { type: string,  default: "http://localhost:8080" }
      compose_service: { type: string, default: "front" }
      test_command: { type: string,  default: "npm run test:e2e" }
permissions: read-all

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: ${{ inputs.node_version }}, cache: 'npm' }
      - name: Install test deps
        run: |
          npm i
          npx playwright install --with-deps
      - name: Build & run app (compose)
        run: |
          docker compose build ${{ inputs.compose_service }}
          docker compose up -d ${{ inputs.compose_service }}
          for i in {1..60}; do curl -fsS "${{ inputs.base_url }}" >/dev/null && break; sleep 1; done
          curl -fsS "${{ inputs.base_url }}" >/dev/null
      - name: Run Playwright tests
        env: { BASE_URL: ${{ inputs.base_url }} }
        run: ${{ inputs.test_command }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn
      - if: always()
        run: docker compose down -v
