name: Release
on:
  push:
    branches: [ main, master ]
    tags: [ v*.*.* ]
permissions: read-all
jobs:
  release:
    uses: <your-org>/ci-lib/.github/workflows/docker-release.yml@v1.0.0
    with:
      registry: docker.io
      image_suffixes: '["service","front"]'
    secrets: inherit

  security:
    needs: [release]
    uses: <your-org>/ci-lib/.github/workflows/security.yml@v1.0.0
    with:
      scan_deps: false
      image_artifact: images-to-scan
    secrets: inherit
