name: Security
on:
  workflow_call:
    inputs:
      scan_deps:     { type: boolean, default: true }
      scan_images:   { type: boolean, default: false }
      image_artifact:{ type: string,  default: "images-to-scan" }
      severity:      { type: string,  default: "medium" }   # low|medium|high|critical
      soft_fail:     { type: boolean, default: true }       # don't fail on findings
    secrets:
      SNYK_TOKEN:
        required: false

permissions: read-all

jobs:
  policy:
    name: Build .snyk policy
    runs-on: ubuntu-latest
    if: ${{ secrets.SNYK_TOKEN != '' }}   # skip on forks / missing token
    steps:
      - uses: actions/checkout@v4
      - name: Apply Snyk ignores (org defaults + optional overlay)
        # ⬇️ this composite lives in THIS CI-LIB repo
        uses: tAIness/ci-lib/.github/actions/apply-snyk-ignores@v1.0.0
        with:
          overlay_csv_path: .snyk-ignores.csv          # optional, in caller repo
      - uses: actions/upload-artifact@v4
        with:
          name: snyk-policy
          path: .snyk

  deps:
    name: Snyk (dependencies)
    runs-on: ubuntu-latest
    needs: [policy]
    if: ${{ inputs.scan_deps && secrets.SNYK_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: snyk-policy
          path: .
      - uses: snyk/actions/setup@v4
      - name: Snyk test (all projects)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        shell: bash
        run: |
          snyk test \
            --all-projects \
            --detection-depth=4 \
            --severity-threshold="${{ inputs.severity }}" \
            --policy-path=.snyk
        continue-on-error: ${{ inputs.soft_fail }}

  images:
    name: Snyk (images)
    runs-on: ubuntu-latest
    needs: [policy]
    if: ${{ inputs.scan_images && secrets.SNYK_TOKEN != '' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image_artifact }}
          path: images
      - uses: actions/download-artifact@v4
        with:
          name: snyk-policy
          path: .
      - uses: snyk/actions/setup@v4
      - name: Scan container images
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        shell: bash
        run: |
          shopt -s nullglob
          files=(images/*.txt)
          if (( ${#files[@]} == 0 )); then
            echo "No image refs to scan"; exit 0
          fi
          for f in "${files[@]}"; do
            img="$(cat "$f")"
            echo "Snyk container test: $img"
            snyk container test "$img" \
              --severity-threshold="${{ inputs.severity }}" \
              --policy-path=.snyk || true
          done
        continue-on-error: ${{ inputs.soft_fail }}
