name: Validate
on:
  workflow_call:
    inputs:
      yamllint_config:
        type: string
        default: ""
      yamllint_strict:
        type: boolean
        default: false

permissions: read-all

jobs:
  yaml-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve yamllint config
        shell: bash
        run: |
          set -euo pipefail
          # 1) explicit input file takes precedence
          if [[ -n "${{ inputs.yamllint_config }}" && -f "${{ inputs.yamllint_config }}" ]]; then
            echo "YAML_CONF=${{ inputs.yamllint_config }}" >> "$GITHUB_ENV"
            exit 0
          fi
          # 2) repo-local config files
          if [[ -f .yamllint.yaml ]]; then
            echo "YAML_CONF=.yamllint.yaml" >> "$GITHUB_ENV"
            exit 0
          fi
          if [[ -f .yamllint.yml ]]; then
            echo "YAML_CONF=.yamllint.yml" >> "$GITHUB_ENV"
            exit 0
          fi
          # 3) fallback org default (write a file without using heredoc)
          mkdir -p .github/ci
          printf '%s\n' \
            'extends: default' \
            'ignore: |' \
            '  node_modules/*' \
            '  content/images/*' \
            '  web/game/assets/*' \
            '  playwright-report/*' \
            '  **/*.spdx.json' \
            'rules:' \
            '  document-start: disable' \
            '  truthy: disable' \
            '  line-length:' \
            '    max: 200' \
            '    level: warning' \
            '  indentation:' \
            '    indent-sequences: false' \
            > .github/ci/.yamllint-org.yaml
          echo "YAML_CONF=.github/ci/.yamllint-org.yaml" >> "$GITHUB_ENV"

      - name: yamllint (entire repo)
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: ${{ env.YAML_CONF }}
          file_or_dir: .
          format: github
          strict: ${{ inputs.yamllint_strict }}
          no_warnings: false

      - name: actionlint (GitHub Actions YAML)
        uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true

      - name: Validate docker-compose.yml (if present)
        shell: bash
        run: |
          if [[ -f docker-compose.yml ]]; then
            docker compose -f docker-compose.yml config -q
          else
            echo "No docker-compose.yml; skipping"
          fi
